/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as ParentCaseIdRouteImport } from './routes/parent.$caseId'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as DemoClassesRouteImport } from './routes/demo.classes'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardInvitationsRouteImport } from './routes/dashboard.invitations'
import { Route as DashboardClassesRouteImport } from './routes/dashboard.classes'
import { Route as DemoClassesIndexRouteImport } from './routes/demo.classes.index'
import { Route as DashboardClassesIndexRouteImport } from './routes/dashboard.classes.index'
import { Route as ParentCaseIdTestsRouteImport } from './routes/parent.$caseId.tests'
import { Route as ParentCaseIdTestRouteImport } from './routes/parent.$caseId.test'
import { Route as ParentCaseIdReportRouteImport } from './routes/parent.$caseId.report'
import { Route as ParentCaseIdProfileRouteImport } from './routes/parent.$caseId.profile'
import { Route as ParentCaseIdOnboardingRouteImport } from './routes/parent.$caseId.onboarding'
import { Route as ParentCaseIdInterviewRouteImport } from './routes/parent.$caseId.interview'
import { Route as ParentCaseIdHkRouteImport } from './routes/parent.$caseId.hk'
import { Route as DemoClassesClassIdRouteImport } from './routes/demo.classes.$classId'
import { Route as DashboardClassesClassIdRouteImport } from './routes/dashboard.classes.$classId'
import { Route as DashboardCasesCaseIdRouteImport } from './routes/dashboard.cases.$caseId'
import { Route as ParentCaseIdTestAssignmentIdRouteImport } from './routes/parent.$caseId.test.$assignmentId'
import { Route as ParentCaseIdResultsIeltsRouteImport } from './routes/parent.$caseId.results.ielts'
import { Route as ParentCaseIdResultsHkdseRouteImport } from './routes/parent.$caseId.results.hkdse'
import { Route as ParentCaseIdResultsCurriculumRouteImport } from './routes/parent.$caseId.results.curriculum'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const ParentCaseIdRoute = ParentCaseIdRouteImport.update({
  id: '/parent/$caseId',
  path: '/parent/$caseId',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoClassesRoute = DemoClassesRouteImport.update({
  id: '/demo/classes',
  path: '/demo/classes',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInvitationsRoute = DashboardInvitationsRouteImport.update({
  id: '/invitations',
  path: '/invitations',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardClassesRoute = DashboardClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => DashboardRoute,
} as any)
const DemoClassesIndexRoute = DemoClassesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DemoClassesRoute,
} as any)
const DashboardClassesIndexRoute = DashboardClassesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardClassesRoute,
} as any)
const ParentCaseIdTestsRoute = ParentCaseIdTestsRouteImport.update({
  id: '/tests',
  path: '/tests',
  getParentRoute: () => ParentCaseIdRoute,
} as any)
const ParentCaseIdTestRoute = ParentCaseIdTestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => ParentCaseIdRoute,
} as any)
const ParentCaseIdReportRoute = ParentCaseIdReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => ParentCaseIdRoute,
} as any)
const ParentCaseIdProfileRoute = ParentCaseIdProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ParentCaseIdRoute,
} as any)
const ParentCaseIdOnboardingRoute = ParentCaseIdOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => ParentCaseIdRoute,
} as any)
const ParentCaseIdInterviewRoute = ParentCaseIdInterviewRouteImport.update({
  id: '/interview',
  path: '/interview',
  getParentRoute: () => ParentCaseIdRoute,
} as any)
const ParentCaseIdHkRoute = ParentCaseIdHkRouteImport.update({
  id: '/hk',
  path: '/hk',
  getParentRoute: () => ParentCaseIdRoute,
} as any)
const DemoClassesClassIdRoute = DemoClassesClassIdRouteImport.update({
  id: '/$classId',
  path: '/$classId',
  getParentRoute: () => DemoClassesRoute,
} as any)
const DashboardClassesClassIdRoute = DashboardClassesClassIdRouteImport.update({
  id: '/$classId',
  path: '/$classId',
  getParentRoute: () => DashboardClassesRoute,
} as any)
const DashboardCasesCaseIdRoute = DashboardCasesCaseIdRouteImport.update({
  id: '/cases/$caseId',
  path: '/cases/$caseId',
  getParentRoute: () => DashboardRoute,
} as any)
const ParentCaseIdTestAssignmentIdRoute =
  ParentCaseIdTestAssignmentIdRouteImport.update({
    id: '/$assignmentId',
    path: '/$assignmentId',
    getParentRoute: () => ParentCaseIdTestRoute,
  } as any)
const ParentCaseIdResultsIeltsRoute =
  ParentCaseIdResultsIeltsRouteImport.update({
    id: '/results/ielts',
    path: '/results/ielts',
    getParentRoute: () => ParentCaseIdRoute,
  } as any)
const ParentCaseIdResultsHkdseRoute =
  ParentCaseIdResultsHkdseRouteImport.update({
    id: '/results/hkdse',
    path: '/results/hkdse',
    getParentRoute: () => ParentCaseIdRoute,
  } as any)
const ParentCaseIdResultsCurriculumRoute =
  ParentCaseIdResultsCurriculumRouteImport.update({
    id: '/results/curriculum',
    path: '/results/curriculum',
    getParentRoute: () => ParentCaseIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/classes': typeof DashboardClassesRouteWithChildren
  '/dashboard/invitations': typeof DashboardInvitationsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/demo/classes': typeof DemoClassesRouteWithChildren
  '/invite/$token': typeof InviteTokenRoute
  '/parent/$caseId': typeof ParentCaseIdRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/cases/$caseId': typeof DashboardCasesCaseIdRoute
  '/dashboard/classes/$classId': typeof DashboardClassesClassIdRoute
  '/demo/classes/$classId': typeof DemoClassesClassIdRoute
  '/parent/$caseId/hk': typeof ParentCaseIdHkRoute
  '/parent/$caseId/interview': typeof ParentCaseIdInterviewRoute
  '/parent/$caseId/onboarding': typeof ParentCaseIdOnboardingRoute
  '/parent/$caseId/profile': typeof ParentCaseIdProfileRoute
  '/parent/$caseId/report': typeof ParentCaseIdReportRoute
  '/parent/$caseId/test': typeof ParentCaseIdTestRouteWithChildren
  '/parent/$caseId/tests': typeof ParentCaseIdTestsRoute
  '/dashboard/classes/': typeof DashboardClassesIndexRoute
  '/demo/classes/': typeof DemoClassesIndexRoute
  '/parent/$caseId/results/curriculum': typeof ParentCaseIdResultsCurriculumRoute
  '/parent/$caseId/results/hkdse': typeof ParentCaseIdResultsHkdseRoute
  '/parent/$caseId/results/ielts': typeof ParentCaseIdResultsIeltsRoute
  '/parent/$caseId/test/$assignmentId': typeof ParentCaseIdTestAssignmentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/invitations': typeof DashboardInvitationsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/parent/$caseId': typeof ParentCaseIdRouteWithChildren
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/cases/$caseId': typeof DashboardCasesCaseIdRoute
  '/dashboard/classes/$classId': typeof DashboardClassesClassIdRoute
  '/demo/classes/$classId': typeof DemoClassesClassIdRoute
  '/parent/$caseId/hk': typeof ParentCaseIdHkRoute
  '/parent/$caseId/interview': typeof ParentCaseIdInterviewRoute
  '/parent/$caseId/onboarding': typeof ParentCaseIdOnboardingRoute
  '/parent/$caseId/profile': typeof ParentCaseIdProfileRoute
  '/parent/$caseId/report': typeof ParentCaseIdReportRoute
  '/parent/$caseId/test': typeof ParentCaseIdTestRouteWithChildren
  '/parent/$caseId/tests': typeof ParentCaseIdTestsRoute
  '/dashboard/classes': typeof DashboardClassesIndexRoute
  '/demo/classes': typeof DemoClassesIndexRoute
  '/parent/$caseId/results/curriculum': typeof ParentCaseIdResultsCurriculumRoute
  '/parent/$caseId/results/hkdse': typeof ParentCaseIdResultsHkdseRoute
  '/parent/$caseId/results/ielts': typeof ParentCaseIdResultsIeltsRoute
  '/parent/$caseId/test/$assignmentId': typeof ParentCaseIdTestAssignmentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/classes': typeof DashboardClassesRouteWithChildren
  '/dashboard/invitations': typeof DashboardInvitationsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/demo/classes': typeof DemoClassesRouteWithChildren
  '/invite/$token': typeof InviteTokenRoute
  '/parent/$caseId': typeof ParentCaseIdRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/cases/$caseId': typeof DashboardCasesCaseIdRoute
  '/dashboard/classes/$classId': typeof DashboardClassesClassIdRoute
  '/demo/classes/$classId': typeof DemoClassesClassIdRoute
  '/parent/$caseId/hk': typeof ParentCaseIdHkRoute
  '/parent/$caseId/interview': typeof ParentCaseIdInterviewRoute
  '/parent/$caseId/onboarding': typeof ParentCaseIdOnboardingRoute
  '/parent/$caseId/profile': typeof ParentCaseIdProfileRoute
  '/parent/$caseId/report': typeof ParentCaseIdReportRoute
  '/parent/$caseId/test': typeof ParentCaseIdTestRouteWithChildren
  '/parent/$caseId/tests': typeof ParentCaseIdTestsRoute
  '/dashboard/classes/': typeof DashboardClassesIndexRoute
  '/demo/classes/': typeof DemoClassesIndexRoute
  '/parent/$caseId/results/curriculum': typeof ParentCaseIdResultsCurriculumRoute
  '/parent/$caseId/results/hkdse': typeof ParentCaseIdResultsHkdseRoute
  '/parent/$caseId/results/ielts': typeof ParentCaseIdResultsIeltsRoute
  '/parent/$caseId/test/$assignmentId': typeof ParentCaseIdTestAssignmentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/dashboard/classes'
    | '/dashboard/invitations'
    | '/dashboard/settings'
    | '/demo/classes'
    | '/invite/$token'
    | '/parent/$caseId'
    | '/dashboard/'
    | '/dashboard/cases/$caseId'
    | '/dashboard/classes/$classId'
    | '/demo/classes/$classId'
    | '/parent/$caseId/hk'
    | '/parent/$caseId/interview'
    | '/parent/$caseId/onboarding'
    | '/parent/$caseId/profile'
    | '/parent/$caseId/report'
    | '/parent/$caseId/test'
    | '/parent/$caseId/tests'
    | '/dashboard/classes/'
    | '/demo/classes/'
    | '/parent/$caseId/results/curriculum'
    | '/parent/$caseId/results/hkdse'
    | '/parent/$caseId/results/ielts'
    | '/parent/$caseId/test/$assignmentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard/invitations'
    | '/dashboard/settings'
    | '/invite/$token'
    | '/parent/$caseId'
    | '/dashboard'
    | '/dashboard/cases/$caseId'
    | '/dashboard/classes/$classId'
    | '/demo/classes/$classId'
    | '/parent/$caseId/hk'
    | '/parent/$caseId/interview'
    | '/parent/$caseId/onboarding'
    | '/parent/$caseId/profile'
    | '/parent/$caseId/report'
    | '/parent/$caseId/test'
    | '/parent/$caseId/tests'
    | '/dashboard/classes'
    | '/demo/classes'
    | '/parent/$caseId/results/curriculum'
    | '/parent/$caseId/results/hkdse'
    | '/parent/$caseId/results/ielts'
    | '/parent/$caseId/test/$assignmentId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/dashboard/classes'
    | '/dashboard/invitations'
    | '/dashboard/settings'
    | '/demo/classes'
    | '/invite/$token'
    | '/parent/$caseId'
    | '/dashboard/'
    | '/dashboard/cases/$caseId'
    | '/dashboard/classes/$classId'
    | '/demo/classes/$classId'
    | '/parent/$caseId/hk'
    | '/parent/$caseId/interview'
    | '/parent/$caseId/onboarding'
    | '/parent/$caseId/profile'
    | '/parent/$caseId/report'
    | '/parent/$caseId/test'
    | '/parent/$caseId/tests'
    | '/dashboard/classes/'
    | '/demo/classes/'
    | '/parent/$caseId/results/curriculum'
    | '/parent/$caseId/results/hkdse'
    | '/parent/$caseId/results/ielts'
    | '/parent/$caseId/test/$assignmentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  DemoClassesRoute: typeof DemoClassesRouteWithChildren
  InviteTokenRoute: typeof InviteTokenRoute
  ParentCaseIdRoute: typeof ParentCaseIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/parent/$caseId': {
      id: '/parent/$caseId'
      path: '/parent/$caseId'
      fullPath: '/parent/$caseId'
      preLoaderRoute: typeof ParentCaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/classes': {
      id: '/demo/classes'
      path: '/demo/classes'
      fullPath: '/demo/classes'
      preLoaderRoute: typeof DemoClassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/invitations': {
      id: '/dashboard/invitations'
      path: '/invitations'
      fullPath: '/dashboard/invitations'
      preLoaderRoute: typeof DashboardInvitationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/classes': {
      id: '/dashboard/classes'
      path: '/classes'
      fullPath: '/dashboard/classes'
      preLoaderRoute: typeof DashboardClassesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/demo/classes/': {
      id: '/demo/classes/'
      path: '/'
      fullPath: '/demo/classes/'
      preLoaderRoute: typeof DemoClassesIndexRouteImport
      parentRoute: typeof DemoClassesRoute
    }
    '/dashboard/classes/': {
      id: '/dashboard/classes/'
      path: '/'
      fullPath: '/dashboard/classes/'
      preLoaderRoute: typeof DashboardClassesIndexRouteImport
      parentRoute: typeof DashboardClassesRoute
    }
    '/parent/$caseId/tests': {
      id: '/parent/$caseId/tests'
      path: '/tests'
      fullPath: '/parent/$caseId/tests'
      preLoaderRoute: typeof ParentCaseIdTestsRouteImport
      parentRoute: typeof ParentCaseIdRoute
    }
    '/parent/$caseId/test': {
      id: '/parent/$caseId/test'
      path: '/test'
      fullPath: '/parent/$caseId/test'
      preLoaderRoute: typeof ParentCaseIdTestRouteImport
      parentRoute: typeof ParentCaseIdRoute
    }
    '/parent/$caseId/report': {
      id: '/parent/$caseId/report'
      path: '/report'
      fullPath: '/parent/$caseId/report'
      preLoaderRoute: typeof ParentCaseIdReportRouteImport
      parentRoute: typeof ParentCaseIdRoute
    }
    '/parent/$caseId/profile': {
      id: '/parent/$caseId/profile'
      path: '/profile'
      fullPath: '/parent/$caseId/profile'
      preLoaderRoute: typeof ParentCaseIdProfileRouteImport
      parentRoute: typeof ParentCaseIdRoute
    }
    '/parent/$caseId/onboarding': {
      id: '/parent/$caseId/onboarding'
      path: '/onboarding'
      fullPath: '/parent/$caseId/onboarding'
      preLoaderRoute: typeof ParentCaseIdOnboardingRouteImport
      parentRoute: typeof ParentCaseIdRoute
    }
    '/parent/$caseId/interview': {
      id: '/parent/$caseId/interview'
      path: '/interview'
      fullPath: '/parent/$caseId/interview'
      preLoaderRoute: typeof ParentCaseIdInterviewRouteImport
      parentRoute: typeof ParentCaseIdRoute
    }
    '/parent/$caseId/hk': {
      id: '/parent/$caseId/hk'
      path: '/hk'
      fullPath: '/parent/$caseId/hk'
      preLoaderRoute: typeof ParentCaseIdHkRouteImport
      parentRoute: typeof ParentCaseIdRoute
    }
    '/demo/classes/$classId': {
      id: '/demo/classes/$classId'
      path: '/$classId'
      fullPath: '/demo/classes/$classId'
      preLoaderRoute: typeof DemoClassesClassIdRouteImport
      parentRoute: typeof DemoClassesRoute
    }
    '/dashboard/classes/$classId': {
      id: '/dashboard/classes/$classId'
      path: '/$classId'
      fullPath: '/dashboard/classes/$classId'
      preLoaderRoute: typeof DashboardClassesClassIdRouteImport
      parentRoute: typeof DashboardClassesRoute
    }
    '/dashboard/cases/$caseId': {
      id: '/dashboard/cases/$caseId'
      path: '/cases/$caseId'
      fullPath: '/dashboard/cases/$caseId'
      preLoaderRoute: typeof DashboardCasesCaseIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/parent/$caseId/test/$assignmentId': {
      id: '/parent/$caseId/test/$assignmentId'
      path: '/$assignmentId'
      fullPath: '/parent/$caseId/test/$assignmentId'
      preLoaderRoute: typeof ParentCaseIdTestAssignmentIdRouteImport
      parentRoute: typeof ParentCaseIdTestRoute
    }
    '/parent/$caseId/results/ielts': {
      id: '/parent/$caseId/results/ielts'
      path: '/results/ielts'
      fullPath: '/parent/$caseId/results/ielts'
      preLoaderRoute: typeof ParentCaseIdResultsIeltsRouteImport
      parentRoute: typeof ParentCaseIdRoute
    }
    '/parent/$caseId/results/hkdse': {
      id: '/parent/$caseId/results/hkdse'
      path: '/results/hkdse'
      fullPath: '/parent/$caseId/results/hkdse'
      preLoaderRoute: typeof ParentCaseIdResultsHkdseRouteImport
      parentRoute: typeof ParentCaseIdRoute
    }
    '/parent/$caseId/results/curriculum': {
      id: '/parent/$caseId/results/curriculum'
      path: '/results/curriculum'
      fullPath: '/parent/$caseId/results/curriculum'
      preLoaderRoute: typeof ParentCaseIdResultsCurriculumRouteImport
      parentRoute: typeof ParentCaseIdRoute
    }
  }
}

interface DashboardClassesRouteChildren {
  DashboardClassesClassIdRoute: typeof DashboardClassesClassIdRoute
  DashboardClassesIndexRoute: typeof DashboardClassesIndexRoute
}

const DashboardClassesRouteChildren: DashboardClassesRouteChildren = {
  DashboardClassesClassIdRoute: DashboardClassesClassIdRoute,
  DashboardClassesIndexRoute: DashboardClassesIndexRoute,
}

const DashboardClassesRouteWithChildren =
  DashboardClassesRoute._addFileChildren(DashboardClassesRouteChildren)

interface DashboardRouteChildren {
  DashboardClassesRoute: typeof DashboardClassesRouteWithChildren
  DashboardInvitationsRoute: typeof DashboardInvitationsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardCasesCaseIdRoute: typeof DashboardCasesCaseIdRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardClassesRoute: DashboardClassesRouteWithChildren,
  DashboardInvitationsRoute: DashboardInvitationsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardCasesCaseIdRoute: DashboardCasesCaseIdRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface DemoClassesRouteChildren {
  DemoClassesClassIdRoute: typeof DemoClassesClassIdRoute
  DemoClassesIndexRoute: typeof DemoClassesIndexRoute
}

const DemoClassesRouteChildren: DemoClassesRouteChildren = {
  DemoClassesClassIdRoute: DemoClassesClassIdRoute,
  DemoClassesIndexRoute: DemoClassesIndexRoute,
}

const DemoClassesRouteWithChildren = DemoClassesRoute._addFileChildren(
  DemoClassesRouteChildren,
)

interface ParentCaseIdTestRouteChildren {
  ParentCaseIdTestAssignmentIdRoute: typeof ParentCaseIdTestAssignmentIdRoute
}

const ParentCaseIdTestRouteChildren: ParentCaseIdTestRouteChildren = {
  ParentCaseIdTestAssignmentIdRoute: ParentCaseIdTestAssignmentIdRoute,
}

const ParentCaseIdTestRouteWithChildren =
  ParentCaseIdTestRoute._addFileChildren(ParentCaseIdTestRouteChildren)

interface ParentCaseIdRouteChildren {
  ParentCaseIdHkRoute: typeof ParentCaseIdHkRoute
  ParentCaseIdInterviewRoute: typeof ParentCaseIdInterviewRoute
  ParentCaseIdOnboardingRoute: typeof ParentCaseIdOnboardingRoute
  ParentCaseIdProfileRoute: typeof ParentCaseIdProfileRoute
  ParentCaseIdReportRoute: typeof ParentCaseIdReportRoute
  ParentCaseIdTestRoute: typeof ParentCaseIdTestRouteWithChildren
  ParentCaseIdTestsRoute: typeof ParentCaseIdTestsRoute
  ParentCaseIdResultsCurriculumRoute: typeof ParentCaseIdResultsCurriculumRoute
  ParentCaseIdResultsHkdseRoute: typeof ParentCaseIdResultsHkdseRoute
  ParentCaseIdResultsIeltsRoute: typeof ParentCaseIdResultsIeltsRoute
}

const ParentCaseIdRouteChildren: ParentCaseIdRouteChildren = {
  ParentCaseIdHkRoute: ParentCaseIdHkRoute,
  ParentCaseIdInterviewRoute: ParentCaseIdInterviewRoute,
  ParentCaseIdOnboardingRoute: ParentCaseIdOnboardingRoute,
  ParentCaseIdProfileRoute: ParentCaseIdProfileRoute,
  ParentCaseIdReportRoute: ParentCaseIdReportRoute,
  ParentCaseIdTestRoute: ParentCaseIdTestRouteWithChildren,
  ParentCaseIdTestsRoute: ParentCaseIdTestsRoute,
  ParentCaseIdResultsCurriculumRoute: ParentCaseIdResultsCurriculumRoute,
  ParentCaseIdResultsHkdseRoute: ParentCaseIdResultsHkdseRoute,
  ParentCaseIdResultsIeltsRoute: ParentCaseIdResultsIeltsRoute,
}

const ParentCaseIdRouteWithChildren = ParentCaseIdRoute._addFileChildren(
  ParentCaseIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  DemoClassesRoute: DemoClassesRouteWithChildren,
  InviteTokenRoute: InviteTokenRoute,
  ParentCaseIdRoute: ParentCaseIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
